import { buildAllowedSet } from "./allowedPaths";

// All browsable Linux config paths.
// This includes the full config until a curated subset is specified.
export const LINUX_ALLOWED_PATHS: string[] = [
  // --- Agent Core ---
  "addons_enabled",
  "addons_max-parallel-instances",
  "agent_disabled",
  "agent_events_queue-hard-limit",
  "agent_events_queue-soft-limit",
  "agent_modules_paths",
  "agent_type",

  // --- Anti-Tamper ---
  "anti_tamper_engine_enabled",
  "anti-tamper_enabled",
  "anti-tamper_executables_allowed_to_modify_files",

  // --- App Inventory ---
  "appinventory_enabled",

  // --- Auto Debug / Dump ---
  "auto_debug_collection_enabled",
  "auto_dump_collection_enabled",
  "auto_dump_collection_throttle_interval",

  // --- Auto File Upload ---
  "auto_file_upload_benign-enabled",
  "auto_file_upload_benign-on-write-executable-files",
  "auto_file_upload_daily-limit",
  "auto_file_upload_default-exclusion-enabled",
  "auto_file_upload_enabled",
  "auto_file_upload_files-limit",
  "auto_file_upload_interval",
  "auto_file_upload_max-disk-usage",
  "auto_file_upload_max-file-size",

  // --- Brute Force ---
  "brute_force_engine_enabled",
  "local_brute_force_attempts_number",
  "local_brute_force_detection_enabled",
  "local_brute_force_time_period",
  "local_brute_force_timeout",
  "remote_ssh_brute_force_attempts_number",
  "remote_ssh_brute_force_detection_enabled",
  "remote_ssh_brute_force_time_period",
  "remote_ssh_brute_force_timeout",

  // --- BTF ---
  "btf_num_candidates",

  // --- Containers ---
  "container_info_fetch_cooldown_period",
  "container_info_fetch_retries",
  "container_info_fetch_retry_delay",
  "container_native_exclusions_enabled",
  "containers_supported",

  // --- CPU Cryptomining ---
  "cpu_cryptomining_threshold",
  "cpu_cryptomining_timewindow_sec",

  // --- Data Model ---
  "data_model_memory_files",
  "data_model_memory_groups",

  // --- Decoy Files (Ransomware) ---
  "decoy_files_manual_paths",
  "decoy_files_manual_paths_enabled",
  "decoy_files_manual_paths_glob_limit",
  "decoy_files_monitor_interval",
  "decoy_files_predefined_paths",
  "decoy_files_predefined_paths_enabled",
  "decoy_files_predefined_paths_glob_limit",
  "decoy_files_suffixes",

  // --- Detectors ---
  "detector_instruction_count_limit",
  "detector_limit_run",
  "detector_telemetry_sample_events",

  // --- Disk Usage ---
  "disk_usage_fs-reserved",
  "disk_usage_monitor-enabled",
  "disk_usage_monitor-interval",
  "disk_usage_upper-limit",

  // --- Drift Detection ---
  "drift_engine_enabled",

  // --- Deep Visibility ---
  "dv_behavioral-indicator",
  "dv_data-mask_all",
  "dv_dns_operation",
  "dv_enabled",
  "dv_event_control_engine_enabled",
  "dv_events-optimization",
  "dv_events-optimization-behavioral-indicator-aggregation",
  "dv_events-optimization-dns-aggregation",
  "dv_events-optimization-exe-whitelist",
  "dv_events-optimization-filecreation-aggregation",
  "dv_events-optimization-filedeletion-aggregation",
  "dv_events-optimization-filemodification-aggregation",
  "dv_events-optimization-filter-undetermined",
  "dv_events-optimization-focused-dv",
  "dv_events-optimization-per-process-blacklist",
  "dv_events-optimization-processcreation-aggregation",
  "dv_events-optimization-script-aggregation",
  "dv_events-optimization-tcpv4-aggregation",
  "dv_events-optimization-tcpv6-aggregation",
  "dv_events-optimization-whitelist",
  "dv_exclusions_asset_max_depth",
  "dv_exclusions_load",
  "dv_exclusions_load_default",
  "dv_exclusions_order_blacklist",
  "dv_file_creation",
  "dv_file_deletion",
  "dv_file_malicious",
  "dv_file_modification",
  "dv_file_rename",
  "dv_http_operation",
  "dv_max_queue_size",
  "dv_metric",
  "dv_metric_count_event_summary",
  "dv_metric_count_exclusion_rules",
  "dv_metric_report_interval",
  "dv_metric_reset_values",
  "dv_number-of-events-in-packet",
  "dv_optimize_file_creations",
  "dv_packet_report_interval",
  "dv_persistency_operation",
  "dv_process_creation",
  "dv_process_exit",
  "dv_process_termination",
  "dv_script_event_directory_scope",
  "dv_script_event_max_content_size",
  "dv_script_event_types",
  "dv_scripts",
  "dv_tcp_incoming",
  "dv_tcp_listen",
  "dv_tcp_outgoing",
  "dv_tcp_v6_incoming",
  "dv_tcp_v6_outgoing",
  "dv_telemetry",
  "dv_use_zstd_for_packet_compression",
  "dv_user_logged-in",
  "dv_user_logged-out",

  // --- Dynamic Spawners ---
  "dynamic_spawners",

  // --- eBPF ---
  "ebpf_allow_missing_caps",
  "ebpf_enabled",
  "ebpf_exclusions_enabled",
  "ebpf_mount_exclusions_enabled",

  // --- Engines ---
  "encryption_utility_heuristic_enabled",
  "engines_dfi",
  "engines_dynamic",

  // --- Events (nested) ---
  "events",
  "events.agent_file_chattr",
  "events.agent_file_chattr.ebpf",
  "events.agent_file_chattr.enabled",
  "events.agent_file_chmod",
  "events.agent_file_chmod.ebpf",
  "events.agent_file_chmod.enabled",
  "events.agent_file_chown",
  "events.agent_file_chown.ebpf",
  "events.agent_file_chown.enabled",
  "events.agent_file_create",
  "events.agent_file_create.ebpf",
  "events.agent_file_create.enabled",
  "events.agent_file_delete",
  "events.agent_file_delete.ebpf",
  "events.agent_file_delete.enabled",
  "events.agent_file_move",
  "events.agent_file_move.ebpf",
  "events.agent_file_move.enabled",
  "events.agent_file_open_write",
  "events.agent_file_open_write.ebpf",
  "events.agent_file_open_write.enabled",
  "events.agent_file_setfattr",
  "events.agent_file_setfattr.ebpf",
  "events.agent_file_setfattr.enabled",
  "events.agent_kill_attempt",
  "events.agent_kill_attempt.ebpf",
  "events.agent_kill_attempt.enabled",
  "events.agent_mount",
  "events.agent_mount.ebpf",
  "events.agent_mount.enabled",
  "events.agent_umount",
  "events.agent_umount.ebpf",
  "events.agent_umount.enabled",
  "events.bash_bind_variable",
  "events.bash_bind_variable.container",
  "events.bash_bind_variable.ebpf",
  "events.bash_bind_variable.enabled",
  "events.bash_netopen",
  "events.bash_netopen.ebpf",
  "events.bash_netopen.enabled",
  "events.bash_readline",
  "events.bash_readline.container",
  "events.bash_readline.ebpf",
  "events.bash_readline.enabled",
  "events.bash_set_signal",
  "events.bash_set_signal.container",
  "events.bash_set_signal.ebpf",
  "events.bash_set_signal.enabled",
  "events.bash_unbind_variable",
  "events.bash_unbind_variable.container",
  "events.bash_unbind_variable.ebpf",
  "events.bash_unbind_variable.enabled",
  "events.chdir",
  "events.chdir.enabled",
  "events.chdir.kprobes",
  "events.chroot",
  "events.chroot.ebpf",
  "events.chroot.enabled",
  "events.commit_creds_pe",
  "events.commit_creds_pe.ebpf",
  "events.commit_creds_pe.enabled",
  "events.containers",
  "events.containers.ebpf",
  "events.containers.enabled",
  "events.containers.kprobes",
  "events.cpu_cryptomining",
  "events.cpu_cryptomining.ebpf",
  "events.cpu_cryptomining.enabled",
  "events.curl_set_proxy",
  "events.curl_set_proxy.ebpf",
  "events.curl_set_proxy.enabled",
  "events.disarm_kprobes",
  "events.disarm_kprobes.ebpf",
  "events.disarm_kprobes.enabled",
  "events.dns_udp",
  "events.dns_udp.ebpf",
  "events.dns_udp.enabled",
  "events.ebpf_program_load",
  "events.ebpf_program_load.ebpf",
  "events.ebpf_program_load.enabled",
  "events.ebpf_program_perf_attach",
  "events.ebpf_program_perf_attach.ebpf",
  "events.ebpf_program_perf_attach.enabled",
  "events.ebpf_program_xdp_attach",
  "events.ebpf_program_xdp_attach.ebpf",
  "events.ebpf_program_xdp_attach.enabled",
  "events.elf_scan",
  "events.elf_scan.enabled",
  "events.execv",
  "events.execv.ebpf",
  "events.execv.enabled",
  "events.execv.kprobes",
  "events.fchdir",
  "events.fchdir.enabled",
  "events.fchdir.kprobes",
  "events.file_chattr",
  "events.file_chattr.ebpf",
  "events.file_chattr.enabled",
  "events.file_chmod",
  "events.file_chmod.ebpf",
  "events.file_chmod.enabled",
  "events.file_chmod.kprobes",
  "events.file_chown",
  "events.file_chown.ebpf",
  "events.file_chown.enabled",
  "events.file_close_write",
  "events.file_close_write.ebpf",
  "events.file_close_write.enabled",
  "events.file_close_write.kprobes",
  "events.file_create",
  "events.file_create.ebpf",
  "events.file_create.enabled",
  "events.file_create.kprobes",
  "events.file_delete",
  "events.file_delete.ebpf",
  "events.file_delete.enabled",
  "events.file_delete.kprobes",
  "events.file_hard_link",
  "events.file_hard_link.ebpf",
  "events.file_hard_link.enabled",
  "events.file_move",
  "events.file_move.ebpf",
  "events.file_move.enabled",
  "events.file_move.kprobes",
  "events.file_read",
  "events.file_read.ebpf",
  "events.file_read.enabled",
  "events.file_time_change",
  "events.file_time_change.ebpf",
  "events.file_time_change.enabled",
  "events.finit_module",
  "events.finit_module.ebpf",
  "events.finit_module.enabled",
  "events.fork_bomb",
  "events.fork_bomb.ebpf",
  "events.fork_bomb.enabled",
  "events.fork_exit",
  "events.fork_exit.ebpf",
  "events.fork_exit.enabled",
  "events.kallsyms_lookup_name",
  "events.kallsyms_lookup_name.ebpf",
  "events.kallsyms_lookup_name.enabled",
  "events.kallsyms_on_each_symbol",
  "events.kallsyms_on_each_symbol.ebpf",
  "events.kallsyms_on_each_symbol.enabled",
  "events.kernel_module_load",
  "events.kernel_module_load.ebpf",
  "events.kernel_module_load.enabled",
  "events.kernel_module_load.kprobes",
  "events.kill",
  "events.kill.ebpf",
  "events.kill.enabled",
  "events.memory_dump",
  "events.memory_dump.ebpf",
  "events.memory_dump.enabled",
  "events.multi_stage_lkm_load",
  "events.multi_stage_lkm_load.ebpf",
  "events.multi_stage_lkm_load.enabled",
  "events.network_info_query",
  "events.network_info_query.ebpf",
  "events.network_info_query.enabled",
  "events.pam_login",
  "events.pam_login.container",
  "events.pam_login.ebpf",
  "events.pam_login.enabled",
  "events.pam_modification",
  "events.pam_modification.enabled",
  "events.piped_execv",
  "events.piped_execv.ebpf",
  "events.piped_execv.enabled",
  "events.prctl_process_rename",
  "events.prctl_process_rename.ebpf",
  "events.prctl_process_rename.enabled",
  "events.process_injection",
  "events.process_injection.ebpf",
  "events.process_injection.enabled",
  "events.ptrace_injection",
  "events.ptrace_injection.ebpf",
  "events.ptrace_injection.enabled",
  "events.ptrace_trace",
  "events.ptrace_trace.ebpf",
  "events.ptrace_trace.enabled",
  "events.python_exec",
  "events.python_exec.container",
  "events.python_exec.ebpf",
  "events.python_exec.enabled",
  "events.setuid_root",
  "events.setuid_root.ebpf",
  "events.setuid_root.enabled",
  "events.socket_filter_attachment",
  "events.socket_filter_attachment.ebpf",
  "events.socket_filter_attachment.enabled",
  "events.software_packing",
  "events.software_packing.ebpf",
  "events.software_packing.enabled",
  "events.system_call_hook",
  "events.system_call_hook.ebpf",
  "events.system_call_hook.enabled",
  "events.tcp_v4_accept",
  "events.tcp_v4_accept.ebpf",
  "events.tcp_v4_accept.enabled",
  "events.tcp_v4_accept.kprobes",
  "events.tcp_v4_connect",
  "events.tcp_v4_connect.ebpf",
  "events.tcp_v4_connect.enabled",
  "events.tcp_v4_connect.kprobes",
  "events.tcp_v6_accept",
  "events.tcp_v6_accept.ebpf",
  "events.tcp_v6_accept.enabled",
  "events.tcp_v6_accept.kprobes",
  "events.tcp_v6_connect",
  "events.tcp_v6_connect.ebpf",
  "events.tcp_v6_connect.enabled",
  "events.tcp_v6_connect.kprobes",
  "events.unauthorized_splice",
  "events.unauthorized_splice.ebpf",
  "events.unauthorized_splice.enabled",
  "events.userspace_exec",
  "events.userspace_exec.ebpf",
  "events.userspace_exec.enabled",

  // --- Events Queue ---
  "events_queue_limit-enabled",
  "extended_detection_logics",

  // --- Fetch / File Integrity ---
  "fetch_metadata_from_container_runtime_service",
  "file_fetch_enabled",
  "file_integrity_enabled",
  "file_read_extended_files_watch_list",
  "file_read_extended_monitoring_enabled",
  "file_read_files_watch_list",
  "file_read_glob_expansion_limit",
  "file-read_update-interval",

  // --- Filters ---
  "filter_internal_cluster_tcp_provider",
  "filter_out_prctl_rename_empty_process_name",
  "filter_tcp_localhost_provider",

  // --- FIPS ---
  "fips_enabled",

  // --- Forensics ---
  "forensics_dynamic-config",
  "forensics_enabled",
  "forensics_maximum-daily-upload",
  "forensics_maximum-file-size-upload",
  "forensics_parsed-artifacts-destination",
  "forensics_results-endpoint",

  // --- Fork Bomb ---
  "fork_bomb_count_threshold",
  "fork_bomb_prevention_enabled",
  "fork_bomb_prevention_time_threshold_ms",
  "fork_bomb_time_window_ms",

  // --- Full Disk Scan ---
  "full_disk_scan_path_exclusions",

  // --- Firewall ---
  "fw-control_enabled",
  "fw-control_interval",
  "fw-control_network-quarantine",
  "fw-control_report-log",
  "fw-control_report-mgmt",

  // --- GLADS ---
  "glads_enabled",

  // --- Health Center (nested) ---
  "health_center",
  "health_center.connectivity",
  "health_center.connectivity.enabled",
  "health_center.connectivity.interval",
  "health_center.disk_metrics",
  "health_center.disk_metrics.enabled",
  "health_center.disk_metrics.interval",
  "health_center.enabled",

  // --- Heap Trimming ---
  "heap_trimming-enabled",
  "heap_trimming-interval",
  "heap_trimming-madvise",

  // --- Heuristical Engine (nested) ---
  "heuristical_engine",
  "heuristical_engine.enabled",
  "heuristical_engine.heuristical_logics",

  // --- Immutability Engine ---
  "immutability_engine_check_image_layer",
  "immutability_engine_enabled",
  "immutability_engine_start_delay",

  // --- Network Filters ---
  "incoming_internal_cluster_subnets_filter",
  "outgoing_internal_cluster_subnets_filter",

  // --- Informational Alerts ---
  "informational_alerts_on",
  "informational_alerts_per_day",
  "informational_alerts_verbosity_level",

  // --- IPT ---
  "ipt_enabled",

  // --- Logging ---
  "log_addon_instance_max-size",
  "log_addons_max-size",
  "log_agent_max-size",
  "log_collector",
  "log_collector.batch_max_bytes_size",
  "log_collector.batch_max_logs_count",
  "log_collector.batch_send_interval",
  "log_collector.checkpoint_enabled",
  "log_collector.checkpoint_on_disablement",
  "log_collector.chunk_size",
  "log_collector.enabled",
  "log_collector.fingerprint_enabled",
  "log_collector.fingerprint_max_bytes",
  "log_collector.fingerprint_num_lines",
  "log_collector.follow_symlinks",
  "log_collector.io_request_wait_count",
  "log_collector.max_line_length",
  "log_collector.max_open_files",
  "log_collector.memory_limit_bytes",
  "log_collector.read_fail_count_limit",
  "log_collector.read_interval",
  "log_collector.read_timeout_ns",
  "log_collector.scan_interval",
  "log_collector.telemetry_enabled",
  "log_communicator_max-size",
  "log_ctl_max-size",
  "log_ctl_min-level",
  "log_detectors_max-size",
  "log_dv_max-size",
  "log_firewall_max-size",
  "log_log_collector_max-size",
  "log_min-level",
  "log_network_max-size",
  "log_orchestrator_max-size",
  "log_perf_max-size",
  "log_providers_init_max_size",
  "log_scanner_max-size",
  "log_stats_interval",
  "log_stats_max-size",
  "log_stats_min-subpath",

  // --- Memory ---
  "memory_tracing_enabled",

  // --- Management ---
  "mgmt_appinventory-force-update",
  "mgmt_appinventory-interval",
  "mgmt_device-type",
  "mgmt_hash-report-interval",
  "mgmt_secured-protocol-mode",
  "mgmt_send-model-name",
  "mgmt_update-machine-info-interval",

  // --- Mitigation ---
  "mitigation_enabled",
  "mitigation_kill",
  "mitigation_kill_limited_mode",
  "mitigation_kill_out_of_model",
  "mitigation_mitigate-suspicious",
  "mitigation_network-quarantine",
  "mitigation_quarantine",
  "mitigation_quarantine-filter_non-exe",
  "mitigation_quarantine-filter_verified",

  // --- Model ---
  "model_prune-interval",

  // --- Mounts ---
  "mounts_excluded-types",

  // --- Network Control ---
  "network_control_backend",
  "network_control_direction_aware_rules",
  "network_control_enabled",
  "network_control_stateful",

  // --- Network Quarantine ---
  "nq-control_enabled",
  "nq-dns_hardening-callback_timeout",
  "nq-dns_hardening-enabled",
  "nq-dns_hardening-keep_alive_interval",
  "nq-dns_hardening-max_consecutive_count",
  "nq-dns_hardening-nameservers",

  // --- Misc ---
  "chdir_optimization_enabled",
  "cmdline_exclusions_enabled",
  "comm_sdk_directory_size",
  "config_override_enabled",
  "config_reset_local_enabled",
  "copied_file_integrity_check_enabled",
  "new_uuid_on_agent_enable",
  "online_authorization_enabled",
  "operation_queue_metrics_step",
  "operation_queue_monitor_window",
  "package_manager_interactions_enabled",

  // --- PAM ---
  "pam_policy_monitor_dir_path",
  "pam_policy_monitor_max_file_count",
  "pam_policy_monitor_max_file_size",
  "pam_service_exclusions",

  // --- Performance ---
  "perf_buffer-size",
  "perf_events_queue-hard-limit",
  "perf_events_queue-soft-limit",

  // --- Packages ---
  "pkg_names_for_binary_integrity_verification_query",

  // --- Policy ---
  "policy_on-execute",
  "policy_on-write",

  // --- Provider Events Mutator ---
  "provider_events_mutator_dns_merger_enabled",
  "provider_events_mutator_dns_merger_event_storage_size",
  "provider_events_mutator_enabled",

  // --- Ptrace ---
  "ptrace_scan_new_entry_points_interval",
  "ptrace_target_cmdline",

  // --- Ranger ---
  "ranger_enabled",

  // --- Ransomware ---
  "ransomware_engine_decision_threshold",
  "ransomware_engine_enabled",
  "ransomware_engine_event_dispatch_threshold",
  "ransomware_engine_fs_activity_activity_mode",
  "ransomware_engine_fs_activity_sensitivity",
  "ransomware_engine_k8s_enabled",
  "ransomware_engine_k8s_entropy_calc_enabled",

  // --- Remote Shell ---
  "remote_shell_enabled",

  // --- Resource Limits ---
  "resource_memory-limit",
  "resource_memory-limit-include-swap",
  "resource_memory-limit-kills-number",
  "resource_memory-limit-kills-time-frame",
  "resource_memory-limit-percent",
  "resource_memory-monitor-mode",
  "resource_memory-monitor-policy",
  "resource_memory-monitor-policy-fixed-process",

  // --- Restart ---
  "restart_on_system_sleep_enabled",
  "restart_on_system_sleep_interval",

  // --- RSO (Remote Script Orchestration) ---
  "rso_always-upload-streams-to-cloud",
  "rso_daily-download-limit",
  "rso_daily-upload-limit",
  "rso_default-local-output-dir",
  "rso_enabled",
  "rso_max-output-file-size",
  "rso_max-package-disk-usage",
  "rso_suppress-dynamic-threats",

  // --- Running Processes ---
  "running_processes_sync_interval_seconds",

  // --- Scanning ---
  "scan-on-rename",
  "scan-on-rename-caches-max-size",
  "sha256_enabled",
  "static_engine_file_types",
  "static-scan_max-file-size",

  // --- System ---
  "system_core_dumping_enabled",
  "system_events_metadata_bucket_duration",
  "system_events_metadata_max_entries",
  "system_events_metadata_span",
  "system_events_monitor_window",
  "system_events_queue_metrics_step",

  // --- Telemetry ---
  "telemetry_enabled",
  "telemetry_interval",
  "telemetry_performance_alert-mode-enabled",
  "telemetry_performance_alert-mode-interval",
  "telemetry_performance_cpu-threshold_agent",
  "telemetry_performance_cpu-threshold_firewall",
  "telemetry_performance_cpu-threshold_log_collector",
  "telemetry_performance_cpu-threshold_network",
  "telemetry_performance_cpu-threshold_orchestrator",
  "telemetry_performance_cpu-threshold_scanner",
  "telemetry_performance_enabled",
  "telemetry_performance_enabled_agent",
  "telemetry_performance_enabled_firewall",
  "telemetry_performance_enabled_log_collector",
  "telemetry_performance_enabled_network",
  "telemetry_performance_enabled_orchestrator",
  "telemetry_performance_enabled_scanner",
  "telemetry_performance_interval",
  "telemetry_performance_memory-threshold_agent",
  "telemetry_performance_memory-threshold_firewall",
  "telemetry_performance_memory-threshold_log_collector",
  "telemetry_performance_memory-threshold_network",
  "telemetry_performance_memory-threshold_orchestrator",
  "telemetry_performance_memory-threshold_scanner",
  "telemetry_performance_update-interval",

  // --- Threats ---
  "threat_fetch_enabled",

  // --- Unauthorized Splice ---
  "unauthorized_splice_monitored_files",

  // --- Updates ---
  "update_enforce_rpm_gpg_sig",

  // --- Uprobes ---
  "uprobes_bash-bind-variable_env_monitor_list",
  "uprobes_containers_enabled",
  "uprobes_containers_max_containers",
  "uprobes_enabled_backported_kernel",

  // --- Watchdog ---
  "watchdog_interval",
];

export const LINUX_ALLOWED_SET = buildAllowedSet(LINUX_ALLOWED_PATHS);
