import { ConfigObject } from "./types";

// Default SentinelOne Linux agent configuration
export const linuxDefaultConfig: ConfigObject = {
  "addons_enabled": true,
  "addons_max-parallel-instances": 1,
  "agent_disabled": false,
  "agent_events_queue-hard-limit": 500000,
  "agent_events_queue-soft-limit": 500000,
  "agent_modules_paths": [],
  "agent_type": "host",
  "anti_tamper_engine_enabled": true,
  "anti-tamper_enabled": false,
  "anti-tamper_executables_allowed_to_modify_files": [],
  "appinventory_enabled": true,
  "auto_debug_collection_enabled": false,
  "auto_dump_collection_enabled": true,
  "auto_dump_collection_throttle_interval": 240,
  "auto_file_upload_benign-enabled": false,
  "auto_file_upload_benign-on-write-executable-files": false,
  "auto_file_upload_daily-limit": 53687091200,
  "auto_file_upload_default-exclusion-enabled": true,
  "auto_file_upload_enabled": false,
  "auto_file_upload_files-limit": 100,
  "auto_file_upload_interval": 10,
  "auto_file_upload_max-disk-usage": 53687091200,
  "auto_file_upload_max-file-size": 10737418240,
  "brute_force_engine_enabled": true,
  "btf_num_candidates": 3,
  "chdir_optimization_enabled": true,
  "cloud_debug_data_expiration_time": 10063071999,
  "cmdline_exclusions_enabled": true,
  "comm_sdk_directory_size": 209715200,
  "config_override_enabled": true,
  "config_reset_local_enabled": true,
  "container_info_fetch_cooldown_period": 60,
  "container_info_fetch_retries": 5,
  "container_info_fetch_retry_delay": 50,
  "container_native_exclusions_enabled": true,
  "containers_supported": true,
  "copied_file_integrity_check_enabled": true,
  "cpu_cryptomining_threshold": 80,
  "cpu_cryptomining_timewindow_sec": 1,
  "data_model_memory_files": 10000,
  "data_model_memory_groups": 10000,
  "decoy_files_manual_paths": [],
  "decoy_files_manual_paths_enabled": false,
  "decoy_files_manual_paths_glob_limit": 10,
  "decoy_files_monitor_interval": 60,
  "decoy_files_predefined_paths": [
    "/var/www",
    "/var/www/html",
    "/var/lib",
    "/var/lib/www",
    "/srv",
    "/root",
    "/usr/share",
    "/usr/share/nginx/html",
    "/usr/local/share",
    "/usr/local/apache2",
    "/etc/nginx",
    "/etc/mysql",
    "/etc/httpd",
    "/etc/apache2"
  ],
  "decoy_files_predefined_paths_enabled": true,
  "decoy_files_predefined_paths_glob_limit": 10,
  "decoy_files_suffixes": [".pdf", ".ini", ".log", ".html"],
  "detector_instruction_count_limit": 1000000,
  "detector_limit_run": true,
  "detector_telemetry_sample_events": true,
  "disk_usage_fs-reserved": 3,
  "disk_usage_monitor-enabled": false,
  "disk_usage_monitor-interval": 1,
  "disk_usage_upper-limit": 95,
  "drift_engine_enabled": true,
  "dv_behavioral-indicator": true,
  "dv_data-mask_all": false,
  "dv_dns_operation": true,
  "dv_enabled": true,
  "dv_event_control_engine_enabled": true,
  "dv_events-optimization": true,
  "dv_events-optimization-behavioral-indicator-aggregation": true,
  "dv_events-optimization-dns-aggregation": true,
  "dv_events-optimization-exe-whitelist": true,
  "dv_events-optimization-filecreation-aggregation": true,
  "dv_events-optimization-filedeletion-aggregation": true,
  "dv_events-optimization-filemodification-aggregation": true,
  "dv_events-optimization-filter-undetermined": true,
  "dv_events-optimization-focused-dv": true,
  "dv_events-optimization-per-process-blacklist": true,
  "dv_events-optimization-processcreation-aggregation": true,
  "dv_events-optimization-script-aggregation": true,
  "dv_events-optimization-tcpv4-aggregation": true,
  "dv_events-optimization-tcpv6-aggregation": true,
  "dv_events-optimization-whitelist": true,
  "dv_exclusions_asset_max_depth": 20,
  "dv_exclusions_load": true,
  "dv_exclusions_load_default": true,
  "dv_exclusions_order_blacklist": [1011, 1012, 1013, 1014, 1015],
  "dv_file_creation": true,
  "dv_file_deletion": true,
  "dv_file_malicious": false,
  "dv_file_modification": true,
  "dv_file_rename": true,
  "dv_http_operation": true,
  "dv_max_queue_size": 50,
  "dv_metric": true,
  "dv_metric_count_event_summary": true,
  "dv_metric_count_exclusion_rules": true,
  "dv_metric_report_interval": 3600,
  "dv_metric_reset_values": true,
  "dv_number-of-events-in-packet": 1000,
  "dv_optimize_file_creations": true,
  "dv_packet_report_interval": 180,
  "dv_persistency_operation": true,
  "dv_process_creation": true,
  "dv_process_exit": false,
  "dv_process_termination": true,
  "dv_script_event_directory_scope": [],
  "dv_script_event_max_content_size": 16384,
  "dv_script_event_types": [
    "python", "sh", "csh", "ksh", "tcsh", "zsh", "ash",
    "nawk", "gawk", "awk", "fish", "tclsh", "luatex",
    "stap", "execlineb", "ksh_bytecode", "bash", "shebang"
  ],
  "dv_scripts": false,
  "dv_tcp_incoming": true,
  "dv_tcp_listen": true,
  "dv_tcp_outgoing": true,
  "dv_tcp_v6_incoming": false,
  "dv_tcp_v6_outgoing": false,
  "dv_telemetry": true,
  "dv_use_zstd_for_packet_compression": true,
  "dv_user_logged-in": true,
  "dv_user_logged-out": true,
  "dynamic_spawners": [],
  "ebpf_allow_missing_caps": true,
  "ebpf_enabled": true,
  "ebpf_exclusions_enabled": true,
  "ebpf_mount_exclusions_enabled": true,
  "encryption_utility_heuristic_enabled": true,
  "engines_dfi": true,
  "engines_dynamic": true,
  "events": {
    "agent_file_chattr": { "ebpf": true, "enabled": true },
    "agent_file_chmod": { "ebpf": true, "enabled": true },
    "agent_file_chown": { "ebpf": true, "enabled": true },
    "agent_file_create": { "ebpf": true, "enabled": true },
    "agent_file_delete": { "ebpf": true, "enabled": true },
    "agent_file_move": { "ebpf": true, "enabled": true },
    "agent_file_open_write": { "ebpf": true, "enabled": true },
    "agent_file_setfattr": { "ebpf": true, "enabled": true },
    "agent_kill_attempt": { "ebpf": true, "enabled": true },
    "agent_mount": { "ebpf": true, "enabled": true },
    "agent_umount": { "ebpf": true, "enabled": true },
    "bash_bind_variable": { "container": true, "ebpf": true, "enabled": true },
    "bash_netopen": { "ebpf": true, "enabled": true },
    "bash_readline": { "container": true, "ebpf": true, "enabled": true },
    "bash_set_signal": { "container": true, "ebpf": true, "enabled": true },
    "bash_unbind_variable": { "container": true, "ebpf": true, "enabled": true },
    "chdir": { "enabled": true, "kprobes": true },
    "chroot": { "ebpf": true, "enabled": true },
    "commit_creds_pe": { "ebpf": true, "enabled": true },
    "containers": { "ebpf": true, "enabled": true, "kprobes": true },
    "cpu_cryptomining": { "ebpf": true, "enabled": true },
    "curl_set_proxy": { "ebpf": true, "enabled": false },
    "disarm_kprobes": { "ebpf": true, "enabled": true },
    "dns_udp": { "ebpf": true, "enabled": true },
    "ebpf_program_load": { "ebpf": true, "enabled": true },
    "ebpf_program_perf_attach": { "ebpf": true, "enabled": true },
    "ebpf_program_xdp_attach": { "ebpf": true, "enabled": true },
    "elf_scan": { "enabled": false },
    "execv": { "ebpf": true, "enabled": true, "kprobes": true },
    "fchdir": { "enabled": true, "kprobes": true },
    "file_chattr": { "ebpf": false, "enabled": false },
    "file_chmod": { "ebpf": true, "enabled": true, "kprobes": true },
    "file_chown": { "ebpf": false, "enabled": false },
    "file_close_write": { "ebpf": true, "enabled": true, "kprobes": true },
    "file_create": { "ebpf": true, "enabled": true, "kprobes": true },
    "file_delete": { "ebpf": true, "enabled": true, "kprobes": true },
    "file_hard_link": { "ebpf": true, "enabled": true },
    "file_move": { "ebpf": true, "enabled": true, "kprobes": true },
    "file_read": { "ebpf": true, "enabled": true },
    "file_time_change": { "ebpf": true, "enabled": false },
    "finit_module": { "ebpf": true, "enabled": true },
    "fork_bomb": { "ebpf": true, "enabled": true },
    "fork_exit": { "ebpf": true, "enabled": true },
    "kallsyms_lookup_name": { "ebpf": true, "enabled": true },
    "kallsyms_on_each_symbol": { "ebpf": true, "enabled": true },
    "kernel_module_load": { "ebpf": true, "enabled": true, "kprobes": true },
    "kill": { "ebpf": true, "enabled": false },
    "memory_dump": { "ebpf": true, "enabled": true },
    "multi_stage_lkm_load": { "ebpf": true, "enabled": true },
    "network_info_query": { "ebpf": true, "enabled": false },
    "pam_login": { "container": false, "ebpf": true, "enabled": true },
    "pam_modification": { "enabled": true },
    "piped_execv": { "ebpf": true, "enabled": true },
    "prctl_process_rename": { "ebpf": true, "enabled": false },
    "process_injection": { "ebpf": true, "enabled": true },
    "ptrace_injection": { "ebpf": true, "enabled": true },
    "ptrace_trace": { "ebpf": true, "enabled": true },
    "python_exec": { "container": true, "ebpf": true, "enabled": true },
    "setuid_root": { "ebpf": false, "enabled": false },
    "socket_filter_attachment": { "ebpf": true, "enabled": true },
    "software_packing": { "ebpf": true, "enabled": true },
    "system_call_hook": { "ebpf": true, "enabled": true },
    "tcp_v4_accept": { "ebpf": true, "enabled": true, "kprobes": true },
    "tcp_v4_connect": { "ebpf": true, "enabled": true, "kprobes": true },
    "tcp_v6_accept": { "ebpf": true, "enabled": true, "kprobes": true },
    "tcp_v6_connect": { "ebpf": true, "enabled": true, "kprobes": true },
    "unauthorized_splice": { "ebpf": true, "enabled": true },
    "userspace_exec": { "ebpf": true, "enabled": true }
  },
  "events_queue_limit-enabled": false,
  "extended_detection_logics": false,
  "fetch_metadata_from_container_runtime_service": true,
  "file_fetch_enabled": true,
  "file_integrity_enabled": true,
  "file_read_extended_files_watch_list": [
    "/etc/passwd", "/etc/group", "/etc/sudoers", "/etc/login.defs",
    "/etc/pam.d/common-password", "/etc/pam.d/system-auth",
    "/etc/security/pwquality.conf", "/etc/default/locale",
    "/etc/locale.conf", "/etc/sysconfig/i18n", "/etc/timezone",
    "/etc/sysconfig/clock", "/etc/localtime", "/home/*/.i18n",
    "/etc/*-release*", "/etc/*_version", "/usr/lib/os-release", "/etc/issue",
    "/var/mail/*", "/var/spool/mail/*", "/home/*/Mail/*", "/root/Mail/*",
    "/home/*/mail/*", "/root/mail/*", "/home/*/Maildir/*", "/root/Maildir/*",
    "/home/*/Mailbox", "/root/Mailbox", "/home/*/mbox", "/root/mbox",
    "/home/*/.mozilla/firefox/*/key4.db", "/proc/version", "/proc/net/*",
    "/sys/class/dmi/id/*", "/proc/scsi/*", "/proc/scsi/*/*",
    "/proc/ide/*", "/proc/ide/*/*", "/proc/bus/input/devices",
    "/var/lib/dpkg/status", "/var/lib/rpm/Packages", "/var/lib/rpm/Name",
    "/var/lib/rpm/rpmdb.sqlite", "/var/lib/rpm/Packages.db",
    "/usr/lib/sysimage/rpm/Packages", "/usr/lib/sysimage/rpm/Name",
    "/usr/lib/sysimage/rpm/rpmdb.sqlite", "/usr/lib/sysimage/rpm/Packages.db",
    "/proc/[1-9]/cmdline", "/proc/[1-9]/comm",
    "/var/log/auth.log", "/var/log/secure", "/var/log/syslog",
    "/var/log/messages", "/var/log/journal/*/*", "/run/log/journal/*/*",
    "/var/log/lastlog", "/var/log/wtmp", "/var/run/utmp",
    "/var/lib/amazon/ssm/Vault/Store/EC2RegistrationKey",
    "/var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token",
    "/var/lib/amazon/ssm/Vault/Store/RegistrationKey",
    "/var/run/secrets/eks.amazonaws.com/serviceaccount/token",
    "/var/lib/amazon/ssm/Vault/Store/InstanceFingerprint",
    "/var/lib/amazon/ssm/credentials",
    "/usr/local/aws-storage-gateway/var/cert.pem",
    "/usr/local/aws-storage-gateway/var/keypair.pem",
    "/etc/boto.cfg", "/root/.aws/credentials",
    "/home/*/.aws/credentials", "/home/*/.aws/config",
    "/home/*/.aws/cache", "/home/*/.boto",
    "/home/*/.aws/sso/cache/*", "/home/*/.azure/*",
    "/home/*/.config/gcloud/*",
    "/var/run/secrets/kubernetes.io/*",
    "/var/run/secrets/kubernetes.io/*/token",
    "/var/run/secrets/kubernetes.io/*/namespace",
    "/var/run/secrets/kubernetes.io/*/ca.crt",
    "/home/*/.docker/config.json",
    "/var/docker/server.pem", "/var/docker/serverkey.pem",
    "/home/*/.kube/config",
    "/sys/class/net/*/*", "/sys/class/hwmon/hwmon*/temp*",
    "/sys/class/thermal/thermal_zone*/temp"
  ],
  "file_read_extended_monitoring_enabled": false,
  "file_read_files_watch_list": [
    "/etc/shadow", "/etc/hosts", "/etc/ssh/ssh_config",
    "/root/.ssh/config", "/home/*/.ssh/config",
    "/root/.ssh/id_*", "/home/*/.ssh/id_*",
    "/root/.ssh/known_hosts", "/home/*/.ssh/known_hosts",
    "/root/.*sh_history", "/home/*/.*sh_history",
    "/sys/devices/system/cpu/online", "/proc/cpuinfo",
    "/sys/devices/system/cpu/cpu0/topology/*",
    "/sys/kernel/mm/hugepages/*/*",
    "/sys/devices/system/node/node0/cpumap",
    "/sys/devices/system/node/node0/meminfo",
    "/proc/diskstats", "/etc/fedora-release", "/etc/SuSE-release",
    "/etc/gentoo-release", "/etc/slackware-version",
    "/etc/mandrake-release", "/proc/vmware/version",
    "/etc/xensource-inventory", "/etc/redhat-release", "/etc/lsb-release",
    "/proc/stat", "/etc/machine-id", "/etc/resolv.conf",
    "/run/resolvconf/resolv.conf", "/run/systemd/resolve/stub-resolv.conf",
    "/home/*/.config/google-chrome/Default/Login Data",
    "/home/*/.config/chromium/Default/Login Data",
    "/snap/chromium/common/chromium/Default/Login Data",
    "/home/*/.mozilla/firefox/*/logins.json",
    "/etc/debian_version", "/tmp/krb5cc_*",
    "/var/lib/sss/secrets/*", "/var/lib/sss/secrets/.*"
  ],
  "file_read_glob_expansion_limit": 100,
  "file-read_update-interval": 300,
  "filter_internal_cluster_tcp_provider": true,
  "filter_out_prctl_rename_empty_process_name": true,
  "filter_tcp_localhost_provider": true,
  "fips_enabled": false,
  "forensics_dynamic-config": {},
  "forensics_enabled": false,
  "forensics_maximum-daily-upload": 21474836480,
  "forensics_maximum-file-size-upload": 10737418240,
  "forensics_parsed-artifacts-destination": "skylight",
  "forensics_results-endpoint": "/api/v1.6/remote-ops/forensics/addon-notification",
  "fork_bomb_count_threshold": 1000,
  "fork_bomb_prevention_enabled": false,
  "fork_bomb_prevention_time_threshold_ms": 50,
  "fork_bomb_time_window_ms": 500,
  "full_disk_scan_path_exclusions": false,
  "fw-control_enabled": true,
  "fw-control_interval": 30,
  "fw-control_network-quarantine": false,
  "fw-control_report-log": false,
  "fw-control_report-mgmt": false,
  "glads_enabled": true,
  "health_center": {
    "connectivity": {
      "enabled": true,
      "interval": 1800
    },
    "disk_metrics": {
      "enabled": true,
      "interval": 86400
    },
    "enabled": true
  },
  "heap_trimming-enabled": true,
  "heap_trimming-interval": 120,
  "heap_trimming-madvise": false,
  "heuristical_engine": {
    "enabled": true,
    "heuristical_logics": {}
  },
  "immutability_engine_check_image_layer": true,
  "immutability_engine_enabled": true,
  "immutability_engine_start_delay": 60,
  "incoming_internal_cluster_subnets_filter": ["10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12"],
  "informational_alerts_on": false,
  "informational_alerts_per_day": 4,
  "informational_alerts_verbosity_level": 2,
  "ipt_enabled": false,
  "local_brute_force_attempts_number": 30,
  "local_brute_force_detection_enabled": true,
  "local_brute_force_time_period": 180,
  "local_brute_force_timeout": 86400,
  "log_addon_instance_max-size": 10485760,
  "log_addons_max-size": 20971520,
  "log_agent_max-size": 104857600,
  "log_collector": {
    "batch_max_bytes_size": 5242880,
    "batch_max_logs_count": 10000,
    "batch_send_interval": 60,
    "checkpoint_enabled": true,
    "checkpoint_on_disablement": true,
    "chunk_size": 102400,
    "enabled": true,
    "fingerprint_enabled": true,
    "fingerprint_max_bytes": 512,
    "fingerprint_num_lines": 1,
    "follow_symlinks": true,
    "io_request_wait_count": 1,
    "max_line_length": 100000,
    "max_open_files": 256,
    "memory_limit_bytes": 5242880,
    "read_fail_count_limit": 3,
    "read_interval": 1,
    "read_timeout_ns": 75000000,
    "scan_interval": 30,
    "telemetry_enabled": true
  },
  "log_communicator_max-size": 104857600,
  "log_ctl_max-size": 10485760,
  "log_ctl_min-level": 1,
  "log_detectors_max-size": 20971520,
  "log_dv_max-size": 20971520,
  "log_firewall_max-size": 11534336,
  "log_log_collector_max-size": 10485760,
  "log_min-level": 1,
  "log_network_max-size": 41943040,
  "log_orchestrator_max-size": 20971520,
  "log_perf_max-size": 104857600,
  "log_providers_init_max_size": 20971520,
  "log_scanner_max-size": 20971520,
  "log_stats_interval": 3600,
  "log_stats_max-size": 10485760,
  "log_stats_min-subpath": 3,
  "memory_tracing_enabled": false,
  "mgmt_appinventory-force-update": 86400,
  "mgmt_appinventory-interval": 600,
  "mgmt_device-type": 1,
  "mgmt_hash-report-interval": 5,
  "mgmt_secured-protocol-mode": 2,
  "mgmt_send-model-name": true,
  "mgmt_update-machine-info-interval": 600,
  "mitigation_enabled": true,
  "mitigation_kill": false,
  "mitigation_kill_limited_mode": false,
  "mitigation_kill_out_of_model": true,
  "mitigation_mitigate-suspicious": false,
  "mitigation_network-quarantine": false,
  "mitigation_quarantine": false,
  "mitigation_quarantine-filter_non-exe": true,
  "mitigation_quarantine-filter_verified": true,
  "model_prune-interval": 5,
  "mounts_excluded-types": [
    "fuse.lxcfs", "cifs", "nfs", "nfs4", "secfs2",
    "ceph", "fuse.glusterfs", "nfsd", "acfs", "omfs", "hdfs"
  ],
  "network_control_backend": "iptables",
  "network_control_direction_aware_rules": false,
  "network_control_enabled": true,
  "network_control_stateful": false,
  "new_uuid_on_agent_enable": false,
  "nq-control_enabled": false,
  "nq-dns_hardening-callback_timeout": 7,
  "nq-dns_hardening-enabled": false,
  "nq-dns_hardening-keep_alive_interval": 60,
  "nq-dns_hardening-max_consecutive_count": 5,
  "nq-dns_hardening-nameservers": [],
  "online_authorization_enabled": true,
  "operation_queue_metrics_step": 60,
  "operation_queue_monitor_window": 180,
  "outgoing_internal_cluster_subnets_filter": ["10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12"],
  "package_manager_interactions_enabled": true,
  "pam_policy_monitor_dir_path": "/etc/pam.d",
  "pam_policy_monitor_max_file_count": 100,
  "pam_policy_monitor_max_file_size": 4096,
  "pam_service_exclusions": ["systemd-user", "cron"],
  "perf_buffer-size": 16777216,
  "perf_events_queue-hard-limit": 500000,
  "perf_events_queue-soft-limit": 500000,
  "pkg_names_for_binary_integrity_verification_query": ["coreutils", "binutils", "openssh-server"],
  "policy_on-execute": true,
  "policy_on-write": true,
  "provider_events_mutator_dns_merger_enabled": true,
  "provider_events_mutator_dns_merger_event_storage_size": 4,
  "provider_events_mutator_enabled": true,
  "ptrace_scan_new_entry_points_interval": 10,
  "ptrace_target_cmdline": [],
  "ranger_enabled": true,
  "ransomware_engine_decision_threshold": 100,
  "ransomware_engine_enabled": true,
  "ransomware_engine_event_dispatch_threshold": 10,
  "ransomware_engine_fs_activity_activity_mode": "on",
  "ransomware_engine_fs_activity_sensitivity": "medium",
  "ransomware_engine_k8s_enabled": true,
  "ransomware_engine_k8s_entropy_calc_enabled": false,
  "remote_shell_enabled": true,
  "remote_ssh_brute_force_attempts_number": 30,
  "remote_ssh_brute_force_detection_enabled": true,
  "remote_ssh_brute_force_time_period": 180,
  "remote_ssh_brute_force_timeout": 86400,
  "resource_memory-limit": 5368709120,
  "resource_memory-limit-include-swap": true,
  "resource_memory-limit-kills-number": 4,
  "resource_memory-limit-kills-time-frame": 2400,
  "resource_memory-limit-percent": 10,
  "resource_memory-monitor-mode": "s1-agent",
  "resource_memory-monitor-policy": "top-consumer",
  "resource_memory-monitor-policy-fixed-process": "agent",
  "restart_on_system_sleep_enabled": true,
  "restart_on_system_sleep_interval": 60,
  "rso_always-upload-streams-to-cloud": false,
  "rso_daily-download-limit": 524288000,
  "rso_daily-upload-limit": 524288000,
  "rso_default-local-output-dir": "/tmp/sentinelone/rso_outputs",
  "rso_enabled": true,
  "rso_max-output-file-size": 262144000,
  "rso_max-package-disk-usage": 2147483648,
  "rso_suppress-dynamic-threats": true,
  "running_processes_sync_interval_seconds": 900,
  "scan-on-rename": true,
  "scan-on-rename-caches-max-size": 10240,
  "sha256_enabled": true,
  "static_engine_file_types": [
    { "type": "@shell-scripts", "enabled": true },
    { "type": "shebang", "enabled": true },
    { "type": "bash", "enabled": true },
    { "type": "ksh_bytecode", "enabled": true },
    { "type": "execlineb", "enabled": true },
    { "type": "ruby", "enabled": true },
    { "type": "elf", "enabled": true },
    { "type": "jsp", "enabled": true },
    { "type": "javascript", "enabled": true },
    { "type": "tar", "enabled": true },
    { "type": "mach_o", "enabled": true },
    { "type": "tcsh", "enabled": true },
    { "type": "eicar", "enabled": true },
    { "type": "pe", "enabled": true },
    { "type": "ksh", "enabled": true },
    { "type": "php", "enabled": true },
    { "type": "gz", "enabled": true },
    { "type": "perl", "enabled": true },
    { "type": "seven_zip", "enabled": true },
    { "type": "zip", "enabled": true },
    { "type": "python_bytecode", "enabled": true },
    { "type": "python", "enabled": true },
    { "type": "rar", "enabled": true },
    { "type": "zsh", "enabled": true },
    { "type": "sh", "enabled": true },
    { "type": "csh", "enabled": true },
    { "type": "ash", "enabled": true },
    { "type": "nawk", "enabled": true },
    { "type": "gawk", "enabled": true },
    { "type": "awk", "enabled": true },
    { "type": "fish", "enabled": true },
    { "type": "tclsh", "enabled": true },
    { "type": "luatex", "enabled": true },
    { "type": "stap", "enabled": true }
  ],
  "static-scan_max-file-size": 31457280,
  "system_core_dumping_enabled": true,
  "system_events_metadata_bucket_duration": 600,
  "system_events_metadata_max_entries": 1000000,
  "system_events_metadata_span": 7200,
  "system_events_monitor_window": 180,
  "system_events_queue_metrics_step": 60,
  "telemetry_enabled": true,
  "telemetry_interval": 3600,
  "telemetry_performance_alert-mode-enabled": false,
  "telemetry_performance_alert-mode-interval": 14400,
  "telemetry_performance_cpu-threshold_agent": 16,
  "telemetry_performance_cpu-threshold_firewall": 8,
  "telemetry_performance_cpu-threshold_log_collector": 8,
  "telemetry_performance_cpu-threshold_network": 8,
  "telemetry_performance_cpu-threshold_orchestrator": 8,
  "telemetry_performance_cpu-threshold_scanner": 8,
  "telemetry_performance_enabled": true,
  "telemetry_performance_enabled_agent": true,
  "telemetry_performance_enabled_firewall": false,
  "telemetry_performance_enabled_log_collector": false,
  "telemetry_performance_enabled_network": false,
  "telemetry_performance_enabled_orchestrator": false,
  "telemetry_performance_enabled_scanner": false,
  "telemetry_performance_interval": 1,
  "telemetry_performance_memory-threshold_agent": 4194304000,
  "telemetry_performance_memory-threshold_firewall": 104857600,
  "telemetry_performance_memory-threshold_log_collector": 104857600,
  "telemetry_performance_memory-threshold_network": 104857600,
  "telemetry_performance_memory-threshold_orchestrator": 104857600,
  "telemetry_performance_memory-threshold_scanner": 104857600,
  "telemetry_performance_update-interval": 3600,
  "threat_fetch_enabled": true,
  "unauthorized_splice_monitored_files": ["/etc/passwd"],
  "update_enforce_rpm_gpg_sig": false,
  "uprobes_bash-bind-variable_env_monitor_list": [
    "HISTORY", "HISTFILE", "HISTSIZE", "HISTFILESIZE",
    "HISTSAVE", "HISTZONE", "HISTLOG", "HISTIGNORE", "HISTCONTROL",
    "HTTP_PROXY", "http_proxy", "HTTPS_PROXY", "https_proxy",
    "FTP_PROXY", "ftp_proxy", "ALL_PROXY", "all_proxy",
    "BASH_EXECUTION_STRING", "LD_PRELOAD", "LD_AUDIT",
    "LD_DYNAMIC_WEAK", "LD_ORIGIN_PATH", "LD_SHOW_AUXV",
    "LD_PREFER_MAP_32BIT_EXEC", "LD_LIBRARY_PATH",
    "SSH_AUTH_SOCK", "KRB5CCNAME", "PROMPT_COMMAND",
    "PS0", "PS1", "PS2", "PS3", "PS4",
    "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"
  ],
  "uprobes_containers_enabled": true,
  "uprobes_containers_max_containers": 100,
  "uprobes_enabled_backported_kernel": false,
  "watchdog_interval": 1
};
