import { buildAllowedSet } from "./allowedPaths";

// All browsable macOS config paths.
// This includes the full config until a curated subset is specified.
export const MACOS_ALLOWED_PATHS: string[] = [
  // --- AddOns ---
  "AddOns",
  "AddOns.ForensicsCPULimit",
  "AddOns.ForensicsDynamicConfig",
  "AddOns.ForensicsDynamicConfig.autoTriggerArtifacts",
  "AddOns.ForensicsEnabled",
  "AddOns.ForensicsLocalDestination",
  "AddOns.ForensicsMaximumDailyUpload",
  "AddOns.ForensicsMaximumFileSizeUpload",
  "AddOns.ForensicsParsedArtifactsDestination",
  "AddOns.ForensicsResultsEndpoint",

  // --- Agent UI ---
  "AgentUI",
  "AgentUI.Capabilities",
  "AgentUI.Capabilities.ContactSupport",
  "AgentUI.Capabilities.DeviceControl",
  "AgentUI.Capabilities.FunctionalProblem",
  "AgentUI.Capabilities.QuarantinedFiles",
  "AgentUI.MaxDeviceEventsCount",
  "AgentUI.MaxDeviceHistoryDays",
  "AgentUI.MaxEventsOverview",
  "AgentUI.MaxLastEventsHistoryDays",
  "AgentUI.MaxQuarantinedFilesCount",
  "AgentUI.MaxThreatsCount",
  "AgentUI.MaxThreatsHistoryDays",
  "AgentUI.ShowAutomaticExternalVolumeScans",
  "AgentUI.ShowDeviceControlEvents",
  "AgentUI.ShowDeviceControlNotifications",
  "AgentUI.ShowSuspiciousThreats",
  "AgentUI.ShowThreatsNotifications",
  "AgentUI.ShowUI",
  "AgentUI.SupportContactCompany",
  "AgentUI.SupportContactDirectMessage",
  "AgentUI.SupportContactEmail",
  "AgentUI.SupportContactFreeText",
  "AgentUI.SupportContactOther",
  "AgentUI.SupportContactPhoneNumber",
  "AgentUI.SupportContactWebsite",
  "AgentUI.Verbose",

  // --- Binary Vault ---
  "BinaryVault",
  "BinaryVault.Enabled",
  "BinaryVault.MaximumFileSize",
  "BinaryVault.RecentUploadCacheDuration",
  "BinaryVault.UploadBenignExecutableFiles",
  "BinaryVault.UploadOnEveryProcessCreation",

  // --- Crash Reporter ---
  "CrashReporter",
  "CrashReporter.Delay",
  "CrashReporter.Enabled",
  "CrashReporter.LogFileDuration",
  "CrashReporter.LogFileEnabled",
  "CrashReporter.LogFileMaxSize",

  // --- Deep Visibility ---
  "DeepVisibility",
  "DeepVisibility.AggregateBehavioralIndicatorsEvents",
  "DeepVisibility.AggregateDNSEvents",
  "DeepVisibility.AggregateFileCreationEvents",
  "DeepVisibility.AggregateFileDeletionEvents",
  "DeepVisibility.AggregateFileModificationEvents",
  "DeepVisibility.AggregateHTTPEvents",
  "DeepVisibility.AggregateProcessExitEvents",
  "DeepVisibility.AggregateProcessTerminationEvents",
  "DeepVisibility.AggregateTCPv4Events",
  "DeepVisibility.AggregateTCPv6Events",
  "DeepVisibility.CollectApplicationInstall",
  "DeepVisibility.CollectApplicationUninstall",
  "DeepVisibility.CollectBackgroundTaskManagement",
  "DeepVisibility.CollectBehavioralIndicators",
  "DeepVisibility.CollectDirectoryServiceAttributeSet",
  "DeepVisibility.CollectDirectoryServiceAttributeValueAdd",
  "DeepVisibility.CollectDirectoryServiceAttributeValueRemove",
  "DeepVisibility.CollectDirectoryServiceGroupAdd",
  "DeepVisibility.CollectDirectoryServiceGroupCreate",
  "DeepVisibility.CollectDirectoryServiceGroupDelete",
  "DeepVisibility.CollectDirectoryServiceGroupRemove",
  "DeepVisibility.CollectDirectoryServiceGroupSet",
  "DeepVisibility.CollectDirectoryServicePasswordModify",
  "DeepVisibility.CollectDirectoryServiceUserCreate",
  "DeepVisibility.CollectDirectoryServiceUserDelete",
  "DeepVisibility.CollectDirectoryServiceUserDisable",
  "DeepVisibility.CollectDirectoryServiceUserEnable",
  "DeepVisibility.CollectDNS",
  "DeepVisibility.CollectFileContent",
  "DeepVisibility.CollectFileCreation",
  "DeepVisibility.CollectFileDeletion",
  "DeepVisibility.CollectFileModification",
  "DeepVisibility.CollectFileOnFds",
  "DeepVisibility.CollectFileRename",
  "DeepVisibility.CollectGatekeeperUserOverride",
  "DeepVisibility.CollectHttp",
  "DeepVisibility.CollectModuleLoad",
  "DeepVisibility.CollectProcessCreation",
  "DeepVisibility.CollectProcessExit",
  "DeepVisibility.CollectProcessInjection",
  "DeepVisibility.CollectProcessTermination",
  "DeepVisibility.CollectProfileAdd",
  "DeepVisibility.CollectProfileRemove",
  "DeepVisibility.CollectShellScriptFileContent",
  "DeepVisibility.CollectSu",
  "DeepVisibility.CollectSudo",
  "DeepVisibility.CollectTCCModify",
  "DeepVisibility.CollectTCPv4Incoming",
  "DeepVisibility.CollectTCPv4Listen",
  "DeepVisibility.CollectTCPv4Outgoing",
  "DeepVisibility.CollectTCPv6Incoming",
  "DeepVisibility.CollectTCPv6Listen",
  "DeepVisibility.CollectTCPv6Outgoing",
  "DeepVisibility.CollectUserLogin",
  "DeepVisibility.CollectUserLogout",
  "DeepVisibility.CollectVolumeMount",
  "DeepVisibility.CollectVolumeUnmount",
  "DeepVisibility.CollectXPCConnect",
  "DeepVisibility.DNSMonitoringSource",
  "DeepVisibility.EnableChromeProfileActivation",
  "DeepVisibility.Enabled",
  "DeepVisibility.EnableDNSMonitoring",
  "DeepVisibility.ExtendedPaths",
  "DeepVisibility.FileContentMaxSize",
  "DeepVisibility.FilterEvents",
  "DeepVisibility.GatherMetricsInterval",
  "DeepVisibility.MaxEventAggregateInterval",
  "DeepVisibility.PacketMaxEventCount",
  "DeepVisibility.SendEventsInterval",
  "DeepVisibility.SendMetricsInterval",
  "DeepVisibility.TraceOnAdd",
  "DeepVisibility.UseQueryPrefixForDNSEventsFromNetworkExtensionSource",
  "DeepVisibility.UseResultPrefixForDNSEventsFromNetworkExtensionSource",

  // --- Detection ---
  "Detection",
  "Detection.ArbiterRepeatMatchesMode",
  "Detection.CheckActiveContentBlacklistForUnknownInterpreters",
  "Detection.ContextCacheLimit",
  "Detection.ContextCacheMetricsEnabled",
  "Detection.DynamicCLIScriptValidationEnabled",
  "Detection.DynamicExtendedPaths",
  "Detection.HashedDataSizeLimit",
  "Detection.IgnoreDownloaders",
  "Detection.IgnoreHackTools",
  "Detection.IgnoreMiners",
  "Detection.IgnorePackers",
  "Detection.IgnorePUPs",
  "Detection.IgnoreSuspiciousTools",
  "Detection.InformationalAlertsEnabled",
  "Detection.InformationalAlertsPerDay",
  "Detection.InformationalAlertsVerbosityLevelThreshold",
  "Detection.MitigateAllActiveContentsForGroup",
  "Detection.PromoteValidate",
  "Detection.ReportBehavioralIndicatorForActiveContentOnProcessCreation",
  "Detection.ReportServiceExecution",
  "Detection.ReputationCheckBenignFiles",
  "Detection.ScanOnWrite",
  "Detection.ScanOnWriteExtendedPaths",
  "Detection.Scripts",
  "Detection.Scripts.applescript",
  "Detection.Scripts.javascript",
  "Detection.Scripts.perl",
  "Detection.Scripts.python",
  "Detection.Scripts.ruby",
  "Detection.Scripts.shell",
  "Detection.Scripts.vba",
  "Detection.SHA1HashedDataSizeLimit",
  "Detection.SHA2HashedDataSizeLimit",
  "Detection.SignaturesDB",
  "Detection.StaticAIArchiveScanPolicy",
  "Detection.StaticAIDepth",
  "Detection.StaticAIELFScanPolicy",
  "Detection.StaticAIMachOScanPolicy",
  "Detection.StaticAIMaxSize",
  "Detection.StaticAIOfficeScanPolicy",
  "Detection.StaticAIPDFScanPolicy",
  "Detection.StaticAIPEScanPolicy",
  "Detection.StaticAIPreemptiveBlock",
  "Detection.StaticAIScan",
  "Detection.StaticAIScanArchives",
  "Detection.StaticAIScanDurationLimit",
  "Detection.StaticAIScanELF",
  "Detection.StaticAIScanEnhanced",
  "Detection.StaticAIScanMachO",
  "Detection.StaticAIScanOffice",
  "Detection.StaticAIScanPDF",
  "Detection.StaticAIScanPE",
  "Detection.ThreatLogsAggregationTimeInterval",
  "Detection.ThreatLogsEnabled",
  "Detection.ThreatLogsMinimumActionLevel",
  "Detection.ThreatLogsMinimumTimeIntervalBetweenUploads",
  "Detection.ThreatLogsTimesPerRule",
  "Detection.ThreatLogsUploadDuration",
  "Detection.ThreatLogsUploadSizeLimit",
  "Detection.UseAppExecutablePathWhenInvalidAppURL",

  // --- Device Control ---
  "DeviceControl",
  "DeviceControl.BLEControlEnabled",
  "DeviceControl.BluetoothControlEnabled",
  "DeviceControl.ConsiderParentUSBDeviceClass",
  "DeviceControl.DisableBLECommunication",
  "DeviceControl.DisallowReadOnlyPermissions",
  "DeviceControl.Enabled",
  "DeviceControl.NotifyUI",
  "DeviceControl.Report",
  "DeviceControl.ReportInternalDevices",

  // --- External Services ---
  "ExternalServices",
  "ExternalServices.LogCollectionServiceURL",

  // --- Firewall ---
  "Firewall",
  "Firewall.AllowLocalModifications",
  "Firewall.AllowNetworkExtensionLoad",
  "Firewall.AllowPFFiltering",
  "Firewall.Enabled",
  "Firewall.LocationAware",
  "Firewall.Log",
  "Firewall.Report",
  "Firewall.SupportFQDNRules",

  // --- General ---
  "General",
  "General.ActiveDirectoryCacheExpiration",
  "General.AntiTamperDisabled",
  "General.AntiTamperFileEventsEnabled",
  "General.ChildProcessReuseEnabled",
  "General.ChildProcessTrackLimit",
  "General.CPUConsumptionLimit",
  "General.CPUUsageHighWaterDuration",
  "General.CPUUsageMetricsDuration",
  "General.CPUUsageMinimumDurationBetweenHighWaterHandling",
  "General.CPUUsageMonitoringEnabled",
  "General.CPUUsageSentineldGuardHighWaterMark",
  "General.CPUUsageSentineldHelperHighWaterMark",
  "General.CPUUsageSentineldHighWaterMark",
  "General.DynamicSubsystem",
  "General.ESAuthExecTimeout",
  "General.ExclusionOptimizationMode",
  "General.ExclusionOptimizationModeSendTelemetries",
  "General.ExternalId",
  "General.GatherHashingMetrics",
  "General.GatherInternalMetrics",
  "General.GatherInternalMetricsInterval",
  "General.GatherNetworkMetrics",
  "General.GatherNetworkMetricsInterval",
  "General.HostnameResolutionTimeout",
  "General.KillExistingNetworkConnections",
  "General.MemoryUsageHighWaterDuration",
  "General.MemoryUsageMinimumDurationBetweenHighWaterHandling",
  "General.MemoryUsageMonitoringEnabled",
  "General.MemoryUsageSentineldGuardHighWaterMark",
  "General.MemoryUsageSentineldHelperHighWaterMark",
  "General.MemoryUsageSentineldHighWaterMark",
  "General.NetworkInterfacesVersion",
  "General.Protection",
  "General.RebootTimeout",
  "General.ReducedThreatCountThreshold",
  "General.SendModelName",
  "General.SendOperationalStateInterval",
  "General.SpawnerToolSeparateProcessGroups",
  "General.StaticSubsystem",
  "General.TerminalExecutionStorylineMode",
  "General.UploadAggregatedMetricsInterval",
  "General.UploadMetrics",
  "General.UploadMetricsInterval",
  "General.UseActiveDirectoryForDomainName",

  // --- Health Center ---
  "HealthCenter",
  "HealthCenter.ConnectivityUpdateInterval",
  "HealthCenter.Enabled",
  "HealthCenter.StateUpdateInterval",

  // --- Location ---
  "Location",
  "Location.DNSServersVersion",
  "Location.Enabled",
  "Location.ReportLocations",

  // --- Log Collection ---
  "LogCollection",
  "LogCollection.BatchSendAttempts",
  "LogCollection.BatchSendInterval",
  "LogCollection.BatchSendMaximumLogMessageCount",
  "LogCollection.BatchSendMaximumSize",
  "LogCollection.BatchSendMaximumUploadTaskCount",
  "LogCollection.Enabled",
  "LogCollection.FilesScanInterval",
  "LogCollection.MaximumNumberOfFilesHandledByRule",
  "LogCollection.MaximumSizeOfLogLine",
  "LogCollection.StorageMaximumDuration",
  "LogCollection.StorageMaximumFileSize",

  // --- Network ---
  "Network",
  "Network.AlwaysAllowDNSRequestsForAll",
  "Network.Quarantine",
  "Network.QuarantineRulesEnabled",
  "Network.QuarantineRulesLocationAware",
  "Network.QuarantineRulesSupportFQDN",
  "Network.ResolveSourceIPs",

  // --- On Demand Scan ---
  "OnDemandScan",
  "OnDemandScan.RightClickScanEnabled",

  // --- Ranger ---
  "Ranger",
  "Ranger.Enabled",
  "Ranger.LogLevel",

  // --- Remediation ---
  "Remediation",
  "Remediation.AutomaticResponses",
  "Remediation.LookupDisk",

  // --- Remote Profile ---
  "RemoteProfile",
  "RemoteProfile.CPUSamplePeriod",
  "RemoteProfile.IncludeMemoryGraphs",
  "RemoteProfile.MaxFileSize",

  // --- Remote Script Orchestration ---
  "RemoteScriptOrchestration",
  "RemoteScriptOrchestration.AlwaysUploadStreamsToCloud",
  "RemoteScriptOrchestration.DailyDownloadLimit",
  "RemoteScriptOrchestration.DailyLimit",
  "RemoteScriptOrchestration.Enabled",
  "RemoteScriptOrchestration.LocalDestinationPath",
  "RemoteScriptOrchestration.MaxFileSize",
  "RemoteScriptOrchestration.MaxPackageDiskUsage",

  // --- Remote Shell ---
  "RemoteShell",
  "RemoteShell.Enabled",

  // --- Scanner ---
  "Scanner",
  "Scanner.AutomaticallyScanDiskImages",
  "Scanner.AutomaticallyScanExternalVolumes",
  "Scanner.AutomaticallyScanNetworkVolumes",
  "Scanner.AutomaticallyScanRemovableMedia",

  // --- Server ---
  "Server",
  "Server.AdHocReputationChunkSize",
  "Server.AdHocReputationEnabled",
  "Server.AdHocReputationMaxFiles",
  "Server.AdHocReputationQueryWait",
  "Server.AdHocReputationTimeout",
  "Server.AuthenticationMethod",
  "Server.FileServicesConnectivityTimeout",
  "Server.GeneralConnectivityTimeout",
  "Server.LogArchiveSizeLimit",
  "Server.ProcessRate",
  "Server.ReputationBatchSize",
  "Server.ReputationCheckInterval",
  "Server.SendApplicationInventory",
  "Server.SingleInstance2",
  "Server.SPMEnabled",
  "Server.UpdateInterval",
  "Server.ValidatePrivilegedRequest",
  "Server.WaitForAssetsAfterReboot",

  // --- State ---
  "State",
  "State.CheckSizeInterval",
  "State.CheckSizeMaxRetry",
  "State.CheckSizeRetryInterval",
  "State.DatabaseWriteBufferSize",
  "State.FileLinkSaturationFactor",
  "State.FileOpenReadonlySaturationFactor",
  "State.FileOpenSaturationFactor",
  "State.FileTruncateSaturationFactor",
  "State.MaximumDatabaseSize",
  "State.MaximumWonkyDatabaseSize",
  "State.ProcExecSaturationFactor",
  "State.ProcExitSaturationFactor",
  "State.SaturationEventsQueueEnabled",
  "State.saturationHighMark",
  "State.saturationLowMark",
  "State.SaturationMetricsEnabled",
  "State.SaturationMode",
  "State.SaturationReductionDisabled",
  "State.SaturationWindowCountThreshold",
  "State.SaturationWindowDuration",
  "State.SaturationWindowEventLimit",
  "State.SpecialSaturationWindowCountThreshold",
  "State.SpecialSaturationWindowDuration",
  "State.SpecialSaturationWindowEventLimit",

  // --- Update ---
  "Update",
  "Update.DownloadAttempts",
  "Update.DownloadInterval",
  "Update.OnlineAuthorizationEnabled",
];

export const MACOS_ALLOWED_SET = buildAllowedSet(MACOS_ALLOWED_PATHS);
