import { ConfigObject } from "./types";

// Default SentinelOne macOS agent configuration
export const macosDefaultConfig: ConfigObject = {
  "AddOns": {
    "ForensicsCPULimit": 30,
    "ForensicsDynamicConfig": {
      "autoTriggerArtifacts": [
        { "artifactType": "processesAndDaemonsListing" },
        { "artifactType": "shellConfig" },
        { "artifactType": "sshConfig" },
        { "artifactType": "networkPorts" }
      ]
    },
    "ForensicsEnabled": true,
    "ForensicsLocalDestination": "",
    "ForensicsMaximumDailyUpload": 21474836480,
    "ForensicsMaximumFileSizeUpload": 10737418240,
    "ForensicsParsedArtifactsDestination": "skylight",
    "ForensicsResultsEndpoint": "/api/v1.6/remote-ops/forensics/addon-notification"
  },
  "AgentUI": {
    "Capabilities": {
      "ContactSupport": false,
      "DeviceControl": false,
      "FunctionalProblem": false,
      "QuarantinedFiles": true
    },
    "MaxDeviceEventsCount": 200,
    "MaxDeviceHistoryDays": 30,
    "MaxEventsOverview": 30,
    "MaxLastEventsHistoryDays": 30,
    "MaxQuarantinedFilesCount": 1000,
    "MaxThreatsCount": 30,
    "MaxThreatsHistoryDays": 30,
    "ShowAutomaticExternalVolumeScans": true,
    "ShowDeviceControlEvents": false,
    "ShowDeviceControlNotifications": true,
    "ShowSuspiciousThreats": true,
    "ShowThreatsNotifications": true,
    "ShowUI": true,
    "SupportContactCompany": "",
    "SupportContactDirectMessage": "",
    "SupportContactEmail": "",
    "SupportContactFreeText": "",
    "SupportContactOther": "",
    "SupportContactPhoneNumber": "",
    "SupportContactWebsite": "",
    "Verbose": false
  },
  "BinaryVault": {
    "Enabled": false,
    "MaximumFileSize": 262144000,
    "RecentUploadCacheDuration": 2592000,
    "UploadBenignExecutableFiles": false,
    "UploadOnEveryProcessCreation": false
  },
  "CrashReporter": {
    "Delay": 300,
    "Enabled": true,
    "LogFileDuration": 7200,
    "LogFileEnabled": true,
    "LogFileMaxSize": 314572800
  },
  "DeepVisibility": {
    "AggregateBehavioralIndicatorsEvents": true,
    "AggregateDNSEvents": true,
    "AggregateFileCreationEvents": true,
    "AggregateFileDeletionEvents": true,
    "AggregateFileModificationEvents": true,
    "AggregateHTTPEvents": true,
    "AggregateProcessExitEvents": true,
    "AggregateProcessTerminationEvents": true,
    "AggregateTCPv4Events": true,
    "AggregateTCPv6Events": true,
    "CollectApplicationInstall": 0,
    "CollectApplicationUninstall": 0,
    "CollectBackgroundTaskManagement": 0,
    "CollectBehavioralIndicators": 0,
    "CollectDirectoryServiceAttributeSet": 0,
    "CollectDirectoryServiceAttributeValueAdd": 0,
    "CollectDirectoryServiceAttributeValueRemove": 0,
    "CollectDirectoryServiceGroupAdd": 0,
    "CollectDirectoryServiceGroupCreate": 0,
    "CollectDirectoryServiceGroupDelete": 0,
    "CollectDirectoryServiceGroupRemove": 0,
    "CollectDirectoryServiceGroupSet": 0,
    "CollectDirectoryServicePasswordModify": 0,
    "CollectDirectoryServiceUserCreate": 0,
    "CollectDirectoryServiceUserDelete": 0,
    "CollectDirectoryServiceUserDisable": 0,
    "CollectDirectoryServiceUserEnable": 0,
    "CollectDNS": 0,
    "CollectFileContent": 0,
    "CollectFileCreation": 0,
    "CollectFileDeletion": 0,
    "CollectFileModification": 0,
    "CollectFileOnFds": 0,
    "CollectFileRename": 0,
    "CollectGatekeeperUserOverride": 0,
    "CollectHttp": 0,
    "CollectModuleLoad": 0,
    "CollectProcessCreation": 0,
    "CollectProcessExit": 0,
    "CollectProcessInjection": 0,
    "CollectProcessTermination": 0,
    "CollectProfileAdd": 0,
    "CollectProfileRemove": 0,
    "CollectShellScriptFileContent": 0,
    "CollectSu": 0,
    "CollectSudo": 0,
    "CollectTCCModify": 0,
    "CollectTCPv4Incoming": 0,
    "CollectTCPv4Listen": 0,
    "CollectTCPv4Outgoing": 0,
    "CollectTCPv6Incoming": 0,
    "CollectTCPv6Listen": 0,
    "CollectTCPv6Outgoing": 0,
    "CollectUserLogin": 0,
    "CollectUserLogout": 0,
    "CollectVolumeMount": 0,
    "CollectVolumeUnmount": 0,
    "CollectXPCConnect": 0,
    "DNSMonitoringSource": 2,
    "EnableChromeProfileActivation": true,
    "Enabled": false,
    "EnableDNSMonitoring": false,
    "ExtendedPaths": false,
    "FileContentMaxSize": 32768,
    "FilterEvents": true,
    "GatherMetricsInterval": 3600,
    "MaxEventAggregateInterval": 60,
    "PacketMaxEventCount": 1000,
    "SendEventsInterval": 300,
    "SendMetricsInterval": 3600,
    "TraceOnAdd": false,
    "UseQueryPrefixForDNSEventsFromNetworkExtensionSource": false,
    "UseResultPrefixForDNSEventsFromNetworkExtensionSource": true
  },
  "Detection": {
    "ArbiterRepeatMatchesMode": 1,
    "CheckActiveContentBlacklistForUnknownInterpreters": true,
    "ContextCacheLimit": 200,
    "ContextCacheMetricsEnabled": false,
    "DynamicCLIScriptValidationEnabled": true,
    "DynamicExtendedPaths": false,
    "HashedDataSizeLimit": 30,
    "IgnoreDownloaders": false,
    "IgnoreHackTools": false,
    "IgnoreMiners": false,
    "IgnorePackers": false,
    "IgnorePUPs": false,
    "IgnoreSuspiciousTools": true,
    "InformationalAlertsEnabled": false,
    "InformationalAlertsPerDay": 4,
    "InformationalAlertsVerbosityLevelThreshold": 2,
    "MitigateAllActiveContentsForGroup": true,
    "PromoteValidate": false,
    "ReportBehavioralIndicatorForActiveContentOnProcessCreation": false,
    "ReportServiceExecution": false,
    "ReputationCheckBenignFiles": true,
    "ScanOnWrite": true,
    "ScanOnWriteExtendedPaths": false,
    "Scripts": {
      "applescript": true,
      "javascript": true,
      "perl": false,
      "python": true,
      "ruby": true,
      "shell": true,
      "vba": true
    },
    "SHA1HashedDataSizeLimit": 30,
    "SHA2HashedDataSizeLimit": 1024,
    "SignaturesDB": true,
    "StaticAIArchiveScanPolicy": "Validate",
    "StaticAIDepth": 2,
    "StaticAIELFScanPolicy": "Validate",
    "StaticAIMachOScanPolicy": "Validate",
    "StaticAIMaxSize": 30,
    "StaticAIOfficeScanPolicy": "Validate",
    "StaticAIPDFScanPolicy": "Validate",
    "StaticAIPEScanPolicy": "Validate",
    "StaticAIPreemptiveBlock": true,
    "StaticAIScan": true,
    "StaticAIScanArchives": false,
    "StaticAIScanDurationLimit": 250,
    "StaticAIScanELF": true,
    "StaticAIScanEnhanced": true,
    "StaticAIScanMachO": true,
    "StaticAIScanOffice": false,
    "StaticAIScanPDF": false,
    "StaticAIScanPE": true,
    "ThreatLogsAggregationTimeInterval": 120,
    "ThreatLogsEnabled": true,
    "ThreatLogsMinimumActionLevel": "Validate",
    "ThreatLogsMinimumTimeIntervalBetweenUploads": 60,
    "ThreatLogsTimesPerRule": 3,
    "ThreatLogsUploadDuration": 120,
    "ThreatLogsUploadSizeLimit": 10485760,
    "UseAppExecutablePathWhenInvalidAppURL": true
  },
  "DeviceControl": {
    "BLEControlEnabled": false,
    "BluetoothControlEnabled": true,
    "ConsiderParentUSBDeviceClass": false,
    "DisableBLECommunication": false,
    "DisallowReadOnlyPermissions": false,
    "Enabled": true,
    "NotifyUI": true,
    "Report": [],
    "ReportInternalDevices": false
  },
  "ExternalServices": {
    "LogCollectionServiceURL": "https://ingest.us1.sentinelone.net"
  },
  "Firewall": {
    "AllowLocalModifications": false,
    "AllowNetworkExtensionLoad": true,
    "AllowPFFiltering": false,
    "Enabled": true,
    "LocationAware": true,
    "Log": true,
    "Report": false,
    "SupportFQDNRules": true
  },
  "General": {
    "ActiveDirectoryCacheExpiration": 10800,
    "AntiTamperDisabled": false,
    "AntiTamperFileEventsEnabled": true,
    "ChildProcessReuseEnabled": true,
    "ChildProcessTrackLimit": 5,
    "CPUConsumptionLimit": 250,
    "CPUUsageHighWaterDuration": 180,
    "CPUUsageMetricsDuration": 60,
    "CPUUsageMinimumDurationBetweenHighWaterHandling": 14400,
    "CPUUsageMonitoringEnabled": true,
    "CPUUsageSentineldGuardHighWaterMark": 50,
    "CPUUsageSentineldHelperHighWaterMark": 50,
    "CPUUsageSentineldHighWaterMark": 50,
    "DynamicSubsystem": true,
    "ESAuthExecTimeout": 250,
    "ExclusionOptimizationMode": 2,
    "ExclusionOptimizationModeSendTelemetries": true,
    "ExternalId": "",
    "GatherHashingMetrics": false,
    "GatherInternalMetrics": false,
    "GatherInternalMetricsInterval": 3600,
    "GatherNetworkMetrics": false,
    "GatherNetworkMetricsInterval": 86400,
    "HostnameResolutionTimeout": 15,
    "KillExistingNetworkConnections": true,
    "MemoryUsageHighWaterDuration": 3600,
    "MemoryUsageMinimumDurationBetweenHighWaterHandling": 604800,
    "MemoryUsageMonitoringEnabled": true,
    "MemoryUsageSentineldGuardHighWaterMark": 104857600,
    "MemoryUsageSentineldHelperHighWaterMark": 104857600,
    "MemoryUsageSentineldHighWaterMark": 419430400,
    "NetworkInterfacesVersion": 1,
    "Protection": true,
    "RebootTimeout": 300,
    "ReducedThreatCountThreshold": 256,
    "SendModelName": true,
    "SendOperationalStateInterval": 60,
    "SpawnerToolSeparateProcessGroups": true,
    "StaticSubsystem": true,
    "TerminalExecutionStorylineMode": 1,
    "UploadAggregatedMetricsInterval": 14400,
    "UploadMetrics": false,
    "UploadMetricsInterval": 3600,
    "UseActiveDirectoryForDomainName": true
  },
  "HealthCenter": {
    "ConnectivityUpdateInterval": 1800,
    "Enabled": true,
    "StateUpdateInterval": 86400
  },
  "Location": {
    "DNSServersVersion": 0,
    "Enabled": true,
    "ReportLocations": true
  },
  "LogCollection": {
    "BatchSendAttempts": 3,
    "BatchSendInterval": 60,
    "BatchSendMaximumLogMessageCount": 10000,
    "BatchSendMaximumSize": 5242880,
    "BatchSendMaximumUploadTaskCount": 2,
    "Enabled": true,
    "FilesScanInterval": 120,
    "MaximumNumberOfFilesHandledByRule": 100,
    "MaximumSizeOfLogLine": 100000,
    "StorageMaximumDuration": 86400,
    "StorageMaximumFileSize": 524288000
  },
  "Network": {
    "AlwaysAllowDNSRequestsForAll": false,
    "Quarantine": false,
    "QuarantineRulesEnabled": false,
    "QuarantineRulesLocationAware": false,
    "QuarantineRulesSupportFQDN": true,
    "ResolveSourceIPs": false
  },
  "OnDemandScan": {
    "RightClickScanEnabled": true
  },
  "Ranger": {
    "Enabled": true,
    "LogLevel": "Info"
  },
  "Remediation": {
    "AutomaticResponses": [
      "kill-threat",
      "quarantine-threat",
      "remediate-threat"
    ],
    "LookupDisk": false
  },
  "RemoteProfile": {
    "CPUSamplePeriod": 5,
    "IncludeMemoryGraphs": false,
    "MaxFileSize": 524288000
  },
  "RemoteScriptOrchestration": {
    "AlwaysUploadStreamsToCloud": false,
    "DailyDownloadLimit": 524288000,
    "DailyLimit": 524288000,
    "Enabled": true,
    "LocalDestinationPath": "/tmp/sentinelone/rso_outputs/",
    "MaxFileSize": 262144000,
    "MaxPackageDiskUsage": 2147483648
  },
  "RemoteShell": {
    "Enabled": false
  },
  "Scanner": {
    "AutomaticallyScanDiskImages": false,
    "AutomaticallyScanExternalVolumes": false,
    "AutomaticallyScanNetworkVolumes": false,
    "AutomaticallyScanRemovableMedia": true
  },
  "Server": {
    "AdHocReputationChunkSize": 10000,
    "AdHocReputationEnabled": true,
    "AdHocReputationMaxFiles": 10000,
    "AdHocReputationQueryWait": 10000,
    "AdHocReputationTimeout": 600000,
    "AuthenticationMethod": 1,
    "FileServicesConnectivityTimeout": 1800,
    "GeneralConnectivityTimeout": 1800,
    "LogArchiveSizeLimit": 188743680,
    "ProcessRate": 10,
    "ReputationBatchSize": 10,
    "ReputationCheckInterval": 120,
    "SendApplicationInventory": true,
    "SingleInstance2": true,
    "SPMEnabled": true,
    "UpdateInterval": 5,
    "ValidatePrivilegedRequest": false,
    "WaitForAssetsAfterReboot": false
  },
  "State": {
    "CheckSizeInterval": 604800,
    "CheckSizeMaxRetry": 3,
    "CheckSizeRetryInterval": 1800,
    "DatabaseWriteBufferSize": 8388608,
    "FileLinkSaturationFactor": 60,
    "FileOpenReadonlySaturationFactor": 0,
    "FileOpenSaturationFactor": 50,
    "FileTruncateSaturationFactor": 70,
    "MaximumDatabaseSize": 1000000000,
    "MaximumWonkyDatabaseSize": 700000000,
    "ProcExecSaturationFactor": 101,
    "ProcExitSaturationFactor": 90,
    "SaturationEventsQueueEnabled": true,
    "saturationHighMark": 10000,
    "saturationLowMark": 5000,
    "SaturationMetricsEnabled": false,
    "SaturationMode": 1,
    "SaturationReductionDisabled": false,
    "SaturationWindowCountThreshold": 3,
    "SaturationWindowDuration": 5,
    "SaturationWindowEventLimit": 700,
    "SpecialSaturationWindowCountThreshold": 3,
    "SpecialSaturationWindowDuration": 3,
    "SpecialSaturationWindowEventLimit": 200
  },
  "Update": {
    "DownloadAttempts": 5,
    "DownloadInterval": 300,
    "OnlineAuthorizationEnabled": true
  }
};
